name: cueron_saan
description: "CUERON SAAN - Enterprise HVAC/R service management platform"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase integration
  supabase_flutter: ^2.5.6
  
  # Navigation
  go_router: ^13.2.4
  
  # State management
  flutter_riverpod: ^2.5.1
  
  # UI components
  material_color_utilities: ^0.8.0
  
  # Utilities
  intl: ^0.19.0
  equatable: ^2.0.5
  
  # Image handling
  image_picker: ^1.0.7
  
  # URL handling
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

  # Fonts (Material 3 uses system fonts by default)
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700